<?php
/**
 * Plugin Name: Baran Khanomy UI Review Enhancements
 * Description: استانداردهای UI گزارش بازبینی دور دوم.
 * Version: 1.0.0
 */
if ( ! defined( 'ABSPATH' ) ) exit;

function bk_ui_review_defaults() { return array(
    'hero_title' => 'آموزش خیاطی، مهارتی برای یک زندگی خلاق',
    'hero_text' => 'با آموزش‌های پروژه‌محور، مهارتت را به یک مسیر واقعی برای ساختن و درآمدزایی تبدیل کن.',
    'hero_primary' => 'شروع یادگیری',
    'hero_secondary' => 'دوره‌ها را ببین',
    'benefit_4_icon' => '',
    'benefit_4_title' => 'تجربه‌ای مطمئن',
    'benefit_4_text' => 'آموزش پروژه‌محور',
); }
function bk_ui_review_get( $key ) { $s=wp_parse_args(get_option('bk_ui_review_settings',array()),bk_ui_review_defaults()); return $s[$key] ?? ''; }
add_action('admin_menu',function(){ add_submenu_page('bk-core-settings','استاندارد رابط کاربری','استاندارد رابط کاربری','manage_options','bk-ui-review','bk_ui_review_page'); });
add_action('admin_init',function(){ register_setting('bk_ui_review_group','bk_ui_review_settings',array('sanitize_callback'=>function($input){$d=bk_ui_review_defaults();$o=array();foreach($d as $k=>$v)$o[$k]=isset($input[$k])?sanitize_textarea_field($input[$k]):$v;if(!empty($input['benefit_4_icon']))$o['benefit_4_icon']=esc_url_raw($input['benefit_4_icon']);return $o;})); });
function bk_ui_review_page(){if(!current_user_can('manage_options'))return;$s=wp_parse_args(get_option('bk_ui_review_settings',array()),bk_ui_review_defaults());?>
<div class="wrap" dir="rtl"><h1>استاندارد رابط کاربری</h1><p>محتوای هیرو و مزیت چهارم از این بخش مدیریت می‌شود.</p><form method="post" action="options.php"><?php settings_fields('bk_ui_review_group');?><h2>هیرو</h2><table class="form-table"><tr><th>عنوان</th><td><input class="large-text" name="bk_ui_review_settings[hero_title]" value="<?php echo esc_attr($s['hero_title']);?>"></td></tr><tr><th>توضیح</th><td><textarea class="large-text" rows="3" name="bk_ui_review_settings[hero_text]"><?php echo esc_textarea($s['hero_text']);?></textarea></td></tr><tr><th>دکمه اصلی</th><td><input class="regular-text" name="bk_ui_review_settings[hero_primary]" value="<?php echo esc_attr($s['hero_primary']);?>"></td></tr><tr><th>دکمه دوم</th><td><input class="regular-text" name="bk_ui_review_settings[hero_secondary]" value="<?php echo esc_attr($s['hero_secondary']);?>"></td></tr></table><h2>مزیت چهارم</h2><table class="form-table"><tr><th>آیکن</th><td><input class="large-text" name="bk_ui_review_settings[benefit_4_icon]" value="<?php echo esc_attr($s['benefit_4_icon']);?>"></td></tr><tr><th>عنوان</th><td><input class="regular-text" name="bk_ui_review_settings[benefit_4_title]" value="<?php echo esc_attr($s['benefit_4_title']);?>"></td></tr><tr><th>توضیح</th><td><input class="regular-text" name="bk_ui_review_settings[benefit_4_text]" value="<?php echo esc_attr($s['benefit_4_text']);?>"></td></tr></table><?php submit_button('ذخیره تنظیمات');?></form></div><?php }
add_action('wp_head',function(){if(is_admin())return;?>
<style id="bk-ui-review-overrides">
:root{--bk-purple:#7f50b0;--bk-purple-dark:#6a4096;--bk-gold:#d79c26;--bk-text:#2b2330;--bk-muted:#766b7c;--bk-border:#eadff1;--bk-tint:#f8effc;--bk-surface:#fbf9fc;--bk-danger:#e73a73}
.bk-btn-gold{color:var(--bk-text)!important;background:var(--bk-gold)!important}.bk-btn{border-radius:12px}.bk-btn:not(.bk-btn-gold),.bk-login,.bk-profile-link{font-size:15px;min-height:44px}.bk-section{padding:80px 0}.bk-benefits-grid{grid-template-columns:repeat(4,1fr);min-height:120px}.bk-benefits-grid>div{min-height:104px;border-left:1px solid var(--bk-border)}.bk-benefit-item{padding:16px 24px}.bk-benefit-icon,.bk-benefit-icon img{width:90px;height:90px;min-width:90px;flex-basis:90px}.bk-benefit-icon{padding:8px;background:var(--bk-tint);border-radius:16px;display:grid;place-items:center;font-size:40px}.bk-benefit-icon img{object-fit:contain;display:block}.bk-benefit-copy strong{font-size:17px!important}.bk-benefit-copy small{font-size:14px!important}.bk-category-image{width:64px;height:64px;padding:8px;background:var(--bk-tint);border-radius:16px}.bk-category-image img{width:100%;height:100%;object-fit:contain}.bk-course-body h3{font-size:17px!important}.bk-course-date{font-size:13px!important;color:var(--bk-muted)!important}.bk-course-body p{font-size:14px}.bk-section-head h2,.bk-section-title h2{font-size:22px}.bk-section-head span,.bk-section-title span{font-size:13px}.bk-footer-grid h3{font-size:17px}.bk-footer-grid a,.bk-footer-grid p{font-size:14px}.bk-search input{font-size:16px!important}.bk-nav a{min-height:44px;display:inline-flex;align-items:center}.bk-testimonial-dots button{min-width:44px;width:44px;height:44px;background:transparent;position:relative}.bk-testimonial-dots button:after{content:"";width:7px;height:7px;border-radius:50%;background:#d9c9e2;display:block;margin:auto}.bk-testimonial-dots button.is-active:after{width:18px;border-radius:8px;background:var(--bk-purple)}.bk-course-grid .bk-course-card:only-child{max-width:300px;margin-inline:auto}
@media(max-width:760px){.bk-section{padding:48px 0}.bk-benefits-grid{grid-template-columns:repeat(2,1fr);min-height:0}.bk-benefits-grid>div{min-height:112px;border-bottom:1px solid var(--bk-border)}.bk-benefit-item{padding:12px 14px}.bk-benefit-icon,.bk-benefit-icon img{width:80px;height:80px;min-width:80px;flex-basis:80px}.bk-benefit-copy strong{font-size:16px!important}.bk-benefit-copy small{font-size:13px!important}.bk-search{width:44px;height:44px;overflow:hidden;justify-content:center;padding:0;border:0;background:transparent}.bk-search input{position:absolute;opacity:0;pointer-events:none;width:1px}.bk-nav a{min-height:44px;padding:10px 8px;border-bottom:1px solid var(--bk-border)}.bk-nav a:last-child{border-bottom:0}}
</style><?php },99);
add_action('wp_footer',function(){if(is_admin())return;?><script>document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.bk-dots').forEach(function(d){var g=d.previousElementSibling;if(g&&g.querySelectorAll('.bk-course-card').length<=1)d.style.display='none';});});</script><?php },99);
add_filter('wp_nav_menu_items',function($items,$args){if(empty($args->theme_location)||'primary'!==$args->theme_location||is_front_page())return $items;$home=home_url('/');foreach(array('courses','categories','mentors','about','testimonials','contact') as $id)$items=str_replace('href="#'.$id.'"','href="'.esc_url($home.'#'.$id).'"',$items);return $items;},20,2);
